name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: chaitanya-pratap-singh
          outputs: |
            assets/github-snake.svg
             assets/github-snake-dark.svg?palette=github-dark
             assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and Push
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "Update snake animation"
          git push
